"""MoMask reproduction components (Guo et al. 2024).

Data, text-encoder and evaluator utilities live in `shared`; this package imports
no other model package. Use `shared.data.H3D263Dataset` for MoMask training data
(standard 263-D HumanML3D features), or `shared.data.CanonicalHumanML3DDataset`
to train on the official `new_joint_vecs` distribution the Guo evaluator expects.
"""

from .models import (
    CodebookResidualTransformer,
    MaskedMotionTransformer,
    MotionRVQVAE,
    ResidualTransformer,
    ResidualVectorQuantizer,
    TokenTransformerConfig,
)
from .constraints import (
    BendAngleConstraint,
    JointPositionConstraint,
    LatentRefinementConfig,
    LatentRefinementResult,
    ParentRelativeJointConstraint,
    TorsoRelativeJointConstraint,
    bend_angle_loss,
    bend_angle_violation,
    bend_angles_from_joints,
    build_parent_relative_joint_constraint,
    build_torso_relative_joint_constraint,
    joint_position_error,
    joint_position_loss,
    parent_relative_joint_error,
    parent_relative_joint_errors,
    parent_relative_joint_loss,
    parent_relative_targets_world,
    refine_motion_latents,
    torso_local_joint_positions,
    torso_relative_joint_error,
    torso_relative_joint_errors,
    torso_relative_joint_loss,
    torso_relative_targets_world,
)
from .scene_constraints import (
    RoomGeometryConstraint,
    SceneObstacle,
    SceneTransform,
    build_scene_transform,
    place_joints_in_scene,
    sample_body_points,
    scene_clearance_violation_components,
    scene_clearance_violations,
    scene_geometry_loss,
    scene_geometry_metrics,
)

__all__ = [
    "ResidualVectorQuantizer",
    "MotionRVQVAE",
    "TokenTransformerConfig",
    "MaskedMotionTransformer",
    "ResidualTransformer",
    "CodebookResidualTransformer",
    "JointPositionConstraint",
    "TorsoRelativeJointConstraint",
    "ParentRelativeJointConstraint",
    "BendAngleConstraint",
    "LatentRefinementConfig",
    "LatentRefinementResult",
    "RoomGeometryConstraint",
    "SceneObstacle",
    "SceneTransform",
    "build_scene_transform",
    "place_joints_in_scene",
    "sample_body_points",
    "scene_clearance_violation_components",
    "scene_clearance_violations",
    "scene_geometry_loss",
    "scene_geometry_metrics",
    "bend_angles_from_joints",
    "joint_position_loss",
    "joint_position_error",
    "build_parent_relative_joint_constraint",
    "build_torso_relative_joint_constraint",
    "parent_relative_joint_loss",
    "parent_relative_joint_error",
    "parent_relative_joint_errors",
    "parent_relative_targets_world",
    "torso_local_joint_positions",
    "torso_relative_joint_loss",
    "torso_relative_joint_error",
    "torso_relative_joint_errors",
    "torso_relative_targets_world",
    "bend_angle_loss",
    "bend_angle_violation",
    "refine_motion_latents",
]
